iterative/mlem.ai

content/docs/api-reference/deploy.md
=> Hide TODOs in api.deploy

content/docs/command-reference/pprint.md
Thanks to @elisno for noticing.
=> Fix pprint example by using --rev flag

content/docs/sidebar.json, content/docs/user-guide/data.md, content/docs/user-guide/remote-projects.md, content/docs/user-guide/remote-repos.md
Closes https://github.com/iterative/mlem.ai/issues/70
I just restored the pages + made sure they follow the new convention after renaming. Not sure if anything more is to be done here?
CC: @aguschin
=> add user guides for data and remote repos

src/@dvcorg/gatsby-theme-iterative/components/Documentation/Layout/SearchForm/index.tsx
Updated crawler config for DocsSearch to the new index `mlemai_doc`.
The results look better and clean as it doesn't include contents from the homepage, footers, etc which we previously had.
Fixes #116
=> Updated docssearch

src/components/Home/Header/index.tsx
Closes https://github.com/iterative/mlem.ai/issues/65
=> home: update slide texts

content/docs/sidebar.json, content/docs/use-cases/dvc.md
=> docs: add missing instruction for MLEM<>DVC workflow

content/docs/get-started/deploying.md
Since we're using another app name now, I'm replacing the old one with the new one.
=> Rename MLEM app and fix couple of mistakes

content/docs/command-reference/serve.md, content/docs/get-started/serving.md, content/docs/user-guide/configuration.md
This is [merged](https://github.com/iterative/mlem/pull/352) and released, now we need to update docs.
=> Docs: replace 💅 with 🖇️

content/docs/use-cases/cicd.md
=> cases: copy edit CI/CD for ML

.github/workflows/deployment-report.js, .github/workflows/link-check-deploy.yml, package.json, yarn.lock
See https://github.com/iterative/dvc.org/pull/3700 for more info
This will need some improvements, but solves a lot of issues as-is
=> Upgrade link check to 0.12

content/docs/sidebar.json, gatsby-config.js, package.json, src/@dvcorg/gatsby-theme-iterative/components/Documentation/RightPanel/index.tsx, yarn.lock
=> Hydration issue pick

content/docs/api-reference/save.md, content/docs/command-reference/pprint.md, content/docs/get-started/saving.md, content/docs/user-guide/basic-concepts.md
docs change for https://github.com/iterative/mlem/pull/370
=> Docs: remove `labels` and `description`

package.json, scripts/clear-cloudflare-cache.js, scripts/heroku-deploy.sh
Similar to https://github.com/iterative/cml.dev/pull/301
=> Clear Cloudflare cache after Heroku deployment

src/components/NavBar/index.tsx
Related: 
- https://github.com/iterative/dvc.org/pull/3890
- https://github.com/iterative/cml.dev/pull/302
=> Add blog to navbar

content/docs/user-guide/deploying/docker.md
Hmm, deployment to docker is pretty straightforward and small. Thus, this page / UG is also small.
I am not sure what more stuff can be added really, any ideas perhaps?
It doesn't make sense to list the configurable parameters here since we already have object references for it + it is easily accessible through `-h`
Let me know what you think about this for UG Docker.
=> user guide for docker

content/docs/get-started/serving.md
Take 2 - Same as #215 but should allow preview, opened from upstream fork (😭 )
=> Serving models - updates

package.json, yarn.lock
- Update gatsby-theme-iterative
=> Fix GTO: Update gatsby-theme-iterative

config/link-check/excluded-links.yml, content/docs/command-reference/config.md, content/docs/command-reference/serve.md, content/docs/contributing/core.md, content/docs/contributing/docs.md, content/docs/object-reference/mlem-abcs.md, content/docs/sidebar.json, content/docs/user-guide/analytics.md, content/docs/user-guide/configuration.md, content/docs/user-guide/dvc.md, content/docs/user-guide/linking.md
close #109 
close #237
used https://github.com/iterative/mlem.ai/actions/runs/3555942619/jobs/5972922677#step:3:617 to check wrong links
=> Fix 404 links

content/docs/api-reference/serve.md
https://mlem-ai-fix-api-serve-ykfqtckb.herokuapp.com/doc/api-reference/serve
=> Fix `api/serve` example

.restyled.yml
=> Add restyled configuration

content/docs/sidebar.json
For some reason it was lost 🤷🏻 
thanks @jorgeorpinel for giving a hint
=> Add page for `mlem config`

content/docs/contributing/docs.md
=> contrib/docs: update `yarn` scripts

content/docs/command-reference/declare.md, content/docs/command-reference/types.md, content/docs/get-started/index.md, content/docs/object-reference/mlem-abcs.md, content/docs/object-reference/mlem-objects.md, content/docs/user-guide/basic-concepts.md, content/docs/user-guide/deploying/index.md, content/docs/user-guide/remote-objects/index.md
Tries to clarify a little around the concept of MLEM types. Not sure we always refer to object types. PTAL
We should probably plan to reorg some of this content so it's more concentrated (currently you have to go to 3-4 pages to figure it out).
=> types: clarify/ relink

content/docs/user-guide/configuration.md
=> guide: sort config options and add `state`

content/docs/user-guide/building/docker.md, content/docs/user-guide/building/index.md, content/docs/user-guide/data/numpy.md, content/docs/user-guide/data/pandas.md, content/docs/user-guide/deploying/docker.md, content/docs/user-guide/deploying/heroku.md, content/docs/user-guide/deploying/index.md, content/docs/user-guide/deploying/kubernetes.md, content/docs/user-guide/deploying/sagemaker.md, content/docs/user-guide/models/catboost.md, content/docs/user-guide/models/lightgbm.md, content/docs/user-guide/models/onnx.md, content/docs/user-guide/models/sklearn.md, content/docs/user-guide/models/tensorflow.md, content/docs/user-guide/models/torch.md, content/docs/user-guide/models/xgboost.md, content/docs/user-guide/serving/fastapi.md, content/docs/user-guide/serving/rabbitmq.md, content/docs/user-guide/serving/streamlit.md, scripts/docs/bootstrap_obj_reference.py
Addressing @jorgeorpinel comments from https://github.com/iterative/mlem.ai/pull/271
@jorgeorpinel, you can review and merge if it looks good. Thanks!
=> Fixing typos

content/docs/command-reference/build.md, content/docs/command-reference/deployment/index.md, content/docs/command-reference/serve.md, content/docs/get-started/index.md, content/docs/object-reference/model/index.md, content/docs/user-guide/basic-concepts.md, content/docs/user-guide/deploying/kubernetes.md, content/docs/user-guide/serving/index.md
- Picking up some stuff from - https://github.com/iterative/mlem.ai/pull/244
- Adding k8s deployment case
- Moving "model codification" to concepts section
=> Getting started - more changes

gatsby-config.js, src/@dvcorg/gatsby-theme-iterative/components/LayoutHeader/OtherToolsPopup/index.tsx, src/components/Home/Header/index.tsx
~Machine Learning Engineering Management~ - no
See [deployed](https://mlem-ai-fix-desc-title-hbswpll.herokuapp.com/)
=> Fix title and description on social and site

content/docs/get-started/index.md, content/docs/user-guide/basic-concepts.md, content/docs/user-guide/serving/rabbitmq.md
Close https://github.com/iterative/mlem.ai/issues/299
=> Fix wrong links

gatsby-config.js, src/pages/index.tsx
title, keywords, twitter handle
=> Editing Home page SEO fields

content/docs/sidebar.json, content/docs/user-guide/deploying/flyio.md, content/docs/user-guide/deploying/heroku.md
=> User-guide: flyio

content/docs/sidebar.json, content/docs/user-guide/sdk.md
cc @denis-akvilon
@omesser - please review
close https://github.com/iterative/mlem/issues/499
=> Mention clients for Java and C#

content/docs/user-guide/deploying/docker.md
https://mlem-ai-aguschin-patch--bxnnpg.herokuapp.com/doc/user-guide/deploying/docker/#example-running-rest-api-service-from-cli
=> Add example on exposing docker ports

content/docs/user-guide/deploying/index.md, content/docs/user-guide/index.md, content/docs/user-guide/serving/index.md
Selected, non conflicting changes from @jorgeorpinel 's PR: https://github.com/iterative/mlem.ai/pull/265
CC @aguschin @jorgeorpinel for review
=> Clarifying existing content - take 2

content/docs/user-guide/dvc.md
https://mlem-ai-dvc-private-rep-yxphuh.herokuapp.com/doc/user-guide/dvc/
close https://github.com/iterative/mlem/issues/528
=> Add explanation on how to work with private repos (DVC+MLEM)

content/docs/user-guide/deploying/flyio.md, content/docs/user-guide/deploying/heroku.md, content/docs/user-guide/serving/index.md
Changes:
- deploying
- flyio - adding makeing requests section
- heroku - cli typo, code fixes
- serving - import fix
=> User Guide updates

content/docs/user-guide/building/index.md
While going through the docs I encountered this issue.
=> Fix building docker arguments

content/docs/user-guide/deploying/flyio.md
Related to https://github.com/iterative/mlem/issues/661
cc @aguschin
=> Add Fly.io organization slug

src/@dvcorg/gatsby-theme-iterative/components/Documentation/Layout/SearchForm/index.tsx
Closes https://github.com/iterative/itops/issues/4903
=> Use new search API key for Algolia
