iterative/mlem.ai

content/linked-terms.js, gatsby-config.js
Only added `mlem ls` cmd alias for now.
Need to add others according to usage. CC: @jorgeorpinel
=> Added simple linker file to add cmd alias and terms

.github/workflows/link-check-all.yml, .github/workflows/link-check-deploy.yml, config/link-check/config.yml, config/link-check/excluded-files.yml, config/link-check/excluded-links.yml, content/docs/contributing/docs.md, package.json, yarn.lock
This PR adds our `repo-link-check` package in both GitHub Actions and local npm scripts, with the same implementation that dvc.org currently has.
=> Add link check

content/docs/command-reference/pprint.md
This PR updates the path argument in the `mlem pprint` command example.
Closes #95
=> Update remote data object path in pprint example

content/docs/use-cases/mlem-mr.md
This fixes a couple of commands in the documentation:
1. listing models from a repo appears appears to either need an explicit `--rev` specified or it should have the `/tree/simple` appended. Not sure which version is preferred.
2. My best attempt at this was using the `simple` branch from the repository. However, that contains different data.
3. The source project is specified by `--sp` rather than `--sr`.
I wasn't sure about another issue: None of the commands seem to work with tags.
=> Fix some commands

gatsby-config.js, gatsby-node.js, package.json, src/utils/hooks/useStars.tsx, yarn.lock
This PR fixes #112 by using a GitHub stars implementation that reflects the one on dvc.org.
The reason we use a custom implementation over `gatsby-source-graphql` is because it doesn't have good options for fallback data if the fetch fails, so we use a custom resolver that queries GitHub with `fetch` if a token is provided or dummy test data otherwise.
=> Fix stars when no github token is provided

src/components/NavBar/index.module.css, src/components/NavBar/index.tsx
Making docs link on navbar visible on mobile view. This is just a quick solution to at least have mobile users easy access to docs and can easily be replaced later. There are better approaches and can be discussed https://github.com/iterative/mlem.ai/issues/117 further.
=> Show docs on navbar on mobile view

config/link-check/config.yml
The whole-repo check had `iterative.ai` as its `rootURL`, when it should be `mlem.ai`, and I never noticed because I hadn't been looking at the whole-site check :facepalm:
=> Use actual rootURL for whole-repo check

content/docs/command-reference/init.md, content/docs/user-guide/remote-objects.md
Closes #126
> There should probably be a separate section (in [Remote Objects](https://mlem.ai/doc/user-guide/remote-projects)) to explain that you can initialize MLEM projects in remote locations and give some motivation (why would I do that). The cmd ref. also should be much more emphatic about this.
=> `init`: cover remote project cases

content/docs/command-reference/import.md, content/docs/use-cases/mlem-mr.md, content/docs/user-guide/remote-objects.md
When we updated `example-mlem-get-started` and removed `simple` branch, we forgot to update it in Docs. Fixing that.
=> Replacing links from `simple` to `main` branch

content/docs/api-reference/apply_remote.md, content/docs/api-reference/build.md, content/docs/api-reference/clone.md, content/docs/api-reference/index.md, content/docs/api-reference/load.md, content/docs/api-reference/load_meta.md, content/docs/api-reference/save.md, content/docs/command-reference/apply.md, content/docs/command-reference/build.md, content/docs/command-reference/import.md, content/docs/command-reference/index.md, content/docs/command-reference/serve.md, content/docs/get-started/building.md, content/docs/get-started/index.md, content/docs/get-started/saving.md, content/docs/use-cases/cicd.md, content/docs/user-guide/extending.md, content/docs/user-guide/mlem-abcs.md, content/docs/user-guide/what-is-mlem.md
Various spelling and grammar improvements, e.g.:
* python -> Python
* docker -> Docker
* DockerHub -> Docker Hub
* Numpy -> NumPy
* pandas -> Pandas
* it's -> its (where applicable)
=> Improve spelling and grammar

gatsby-config.js, package.json, yarn.lock
The markdown image on docs was not loading properly.
cc: @madhur-tandon 
>I am unable to use pictures inside the docs
shouldn't [](/static/img/ecr.png) have just worked?
Is there any example I can see? I think [mlem.ai](http://mlem.ai/) doesn't have any pics
so what I get is this:
> >`Error: No matching file found for src "/img/ecr.png" in static folder "static". Please check static folder name and that file exists at "static/img
/ecr.png". This error will probably cause a "GraphQLDocumentError" later in build. All converted field paths MUST resolve to a matching file in the
"static" folder.`
=> Fix image path issue

gatsby-config.js, package.json, sentry.config.js, yarn.lock
gatsby-theme-iterative ~v0.1.15 broke sentry integration on accident, and given there being difficulty with packing sentry with the theme because of how `sentry.config.js` works, we've opted to at least temporarily have the consumer site declare `@sentry/gatsby` in its `gatsby-config.js` and be able to consume a default config provided by the package. This could change when we figure out a better implementation, but this is primarily to just get sentry working again.
=> Re-add Sentry for theme v0.1.16

src/utils/hooks/useStars.tsx
This PR adds a query to the stars request made by this website to use the repo for the project in question, where it currently is pulling from dvc.
https://github.com/iterative/cml.dev/pull/363 is the same thing for cml.dev
=> Fix stars pulling from DVC

content/docs/user-guide/dvc.md, yarn.lock
=> MLEM - DVC interaction update

package.json, src/components/SEO/index.tsx, yarn.lock
https://github.com/iterative/dvc.org/pull/4112 = https://github.com/iterative/iterative.ai/pull/686 = https://github.com/iterative/mlem.ai/pull/221 = https://github.com/iterative/cml.dev/pull/373
This PR consumes the maintenance version of `gatsby-theme-iterative`, which includes specifically the plausible fixes without the recent breaking changes. This will allow us to get this plausible fix without blocking it behind other changes needed to upgrade to the new breaking version.
=> Upgrade theme to 0.1.23 to fix Plausible

content/docs/get-started/applying.md
Closes #213 (mostly)
- Removing warning that sklearn would spew from `predict.py` when predicting on array without features while the model was fitted with features (in `train.py`)
- quotes for import type argument `--it "pandas[csv]"` due to `[` needing quoting or escaping in [zsh](https://zsh.sourceforge.io/Guide/zshguide05.html#l137) (fine in bash)
- wrong inference result
- `mlem apply` returning a boring nothing - we'll use `--method predict_proba` to do the same as in the code scenario
Note: some issues still remain - namely `mlem apply` command output is wrong
=> Applying models - code and CLI fixes

package.json, yarn.lock
This PR takes #199 and updates mlem.ai to `@dvcorg/gatsby-theme-iterative`, a maintenance backport adding the `args-linker` fix in a fully compatible way that we can get the fix in ASAP and unblock GTO docs.
=> Update theme to 0.1.24 for GTO docs args linker fix

content/docs/object-reference/mlem-abcs.md
The page title is an H1 so we can't really use more H1s. Also, there's lots of H2 headings in this page, which causes a super long (not useful) CONTENT nav.
p.s. there's a small engine bug when an H2 text is a repeat of an earlier heading: the scrolling jumps to the first instance, not to the H2 in question.
<details>
Specifically, rn https://mlem.ai/doc/object-reference/mlem-abcs#storage goes to the H1 before the H2 that causes the CONTENT nav entry:
> Also, note that https://github.com/iterative/gatsby-theme-iterative/issues/38 is manifested above, as the highlighted CONTENT nav entry is **Artifact** (should be Storage).
</details>
=> guide: good heading rankings (MLEM ABCs)

package.json, yarn.lock
Similar to https://github.com/iterative/iterative.ai/pull/704 for `mlem.ai`.
https://securityheaders.com/?q=https%3A%2F%2Fmlem-ai-security-header-6cq3fp.herokuapp.com%2F&followRedirects=on
=> Add missing security headers

content/docs/command-reference/serve.md, content/docs/get-started/index.md, content/docs/user-guide/building/index.md, content/docs/user-guide/deploying/kubernetes.md, content/docs/user-guide/dvc.md
Per https://github.com/iterative/mlem.ai/pull/238#pullrequestreview-1210738479
=> term: avoid "tutorial"

content/docs/api-reference/save.md, content/docs/command-reference/apply-remote.md, content/docs/command-reference/migrate.md, content/docs/command-reference/serve.md, content/docs/object-reference/build/docker.md, content/docs/object-reference/deployment/docker.md, content/docs/object-reference/deployment/heroku.md, content/docs/object-reference/deployment/kubernetes.md, content/docs/object-reference/deployment/sagemaker.md, content/docs/object-reference/serving/builtin.md, content/docs/object-reference/serving/rabbitmq.md, content/docs/object-reference/serving/sagemaker.md, content/docs/object-reference/serving/streamlit.md, content/docs/object-reference/uri/git.md, content/docs/sidebar.json, content/docs/user-guide/models/index.md, content/docs/user-guide/serving/fastapi.md, content/docs/user-guide/serving/streamlit.md, scripts/docs/utils.py
Significantly changed pages:
- https://mlem-ai-release-0-4-0-paqi5ijw.herokuapp.com/doc/user-guide/serving/streamlit
- https://mlem-ai-release-0-4-0-paqi5ijw.herokuapp.com/doc/user-guide/models
- https://mlem-ai-release-0-4-0-paqi5ijw.herokuapp.com/doc/api-reference/save
This is for 0.4.0 release of MLEM
=> Add `streamlit` and `preprocess`/`postprocess` to docs

content/docs/contributing/docs.md
Same as https://github.com/iterative/dvc.org/pull/4224
=> contrib/docs: Node version

content/docs/get-started/index.md, content/docs/sidebar.json
- minor typo import fix
-`pandas` was not imported here on the [get-started](https://mlem.ai/doc/get-started/?tab=Python-Code#getting-model-predictions) page
- page redirect fix
- [Working with models](https://mlem.ai/doc/user-guide/models/#working-with-models) after clicking next, it was not going to the next page. 
-  same with [Working with data](https://mlem.ai/doc/user-guide/data/#working-with-data) and  [Importing existing files
](https://mlem.ai/doc/user-guide/importing/#importing-existing-files)
I am not sure if the page not redirecting to the next page was intentional. However, I have made a small change to my PR fixing it. 
Thanks
=> fix: typo and page redirect 

content/docs/user-guide/dvc.md
Adding a note about tokens coming from command line, which could enable workflows like this:
```bash
$ GITHUB_USERNAME=igordertigor GITHUB_TOKEN=$(gh auth token) mlem ...
```
=> Token can come from command line too.
